### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by natronics** [hgb2/PSAS-Capstone#18]
Now that the project is coming along, I think it would be helpful to have some CI service automatically try and build the project. This often helps assure that everything needed is checked in, and that dependencies are available. It's not so important that _every_ build passes, especially in early stages like this, but its also nice to know when it does.

I've had lots of success with [travis](https://travis-ci.org/), you can see a reasonably complete, though overkill, Rust example here:

https://github.com/natronics/rust-fc/blob/master/.travis.yml

This particular project also builds docs (cargo doc) and deploys them to `gh-pages`, so that this page is always up-to-date:

https://natronics.github.io/rust-fc/

Travis also has pretty complete docs for itself:

https://docs.travis-ci.com/user/languages/rust/

You might also want to reference one of my projects that runs JSBSim in Travis(!):

https://github.com/open-aerospace/Lambda-4S/blob/master/.travis.yml

I can also help debug any trouble you have with it.

**Comment by chrisliebert** [comment]
https://travis-ci.org/hgb2/PSAS-Capstone
